#pragma once
#include <Windows.h>
#include <cstdint>
#include <string>
#include <string_view>
#include "..\_Script_Engine\AnimInstance.hpp"
namespace _Game_Player_Mommy_GimbalMommyLongLegs_BP_NetworkMommy {
struct BP_NetworkMommy_C;
}
namespace _Script_CoreUObject {
struct Class;
}
namespace _Script_Engine {
struct PoseLink;
}
namespace _Game_World_Geometry_Characters_MommyLongLegs_Animations_ABP_MommyLongLegs {
#pragma pack(push, 1)
struct ABP_MommyLongLegs_C : public _Script_Engine::AnimInstance {
    private: char pad_2c0[0x8a90]; public:
    void* get_UberGraphFrame();
    void* get_AnimGraphNode_ModifyBone_16();
    void* get_AnimGraphNode_ControlRig_5();
    void* get_AnimGraphNode_LayeredBoneBlend_10();
    void* get_AnimGraphNode_TransitionResult_17();
    void* get_AnimGraphNode_TransitionResult_16();
    void* get_AnimGraphNode_TransitionResult_15();
    void* get_AnimGraphNode_TransitionResult_14();
    void* get_AnimGraphNode_TransitionResult_13();
    void* get_AnimGraphNode_TransitionResult_12();
    void* get_AnimGraphNode_TransitionResult_11();
    void* get_AnimGraphNode_TransitionResult_10();
    void* get_AnimGraphNode_TransitionResult_9();
    void* get_AnimGraphNode_ComponentToLocalSpace_10();
    void* get_AnimGraphNode_ModifyBone_15();
    void* get_AnimGraphNode_ModifyBone_14();
    void* get_AnimGraphNode_LocalToComponentSpace_10();
    void* get_AnimGraphNode_ModifyBone_13();
    void* get_AnimGraphNode_UseCachedPose_25();
    void* get_AnimGraphNode_StateResult_12();
    void* get_AnimGraphNode_SpringBone_3();
    void* get_AnimGraphNode_SpringBone_2();
    void* get_AnimGraphNode_SpringBone_1();
    void* get_AnimGraphNode_ComponentToLocalSpace_9();
    void* get_AnimGraphNode_LocalToComponentSpace_9();
    void* get_AnimGraphNode_SpringBone();
    void* get_AnimGraphNode_SequencePlayer_14();
    void* get_AnimGraphNode_StateResult_11();
    void* get_AnimGraphNode_UseCachedPose_24();
    void* get_AnimGraphNode_StateResult_10();
    void* get_AnimGraphNode_UseCachedPose_23();
    void* get_AnimGraphNode_StateResult_9();
    void* get_AnimGraphNode_UseCachedPose_22();
    void* get_AnimGraphNode_StateResult_8();
    void* get_AnimGraphNode_StateMachine_3();
    void* get_AnimGraphNode_ModifyBone_12();
    void* get_AnimGraphNode_SequencePlayer_13();
    void* get_AnimGraphNode_LocalToComponentSpace_8();
    void* get_AnimGraphNode_RotateRootBone_4();
    void* get_AnimGraphNode_ResetRoot_3();
    void* get_AnimGraphNode_ComponentToLocalSpace_8();
    void* get_AnimGraphNode_ModifyBone_11();
    void* get_AnimGraphNode_ModifyBone_10();
    void* get_AnimGraphNode_ModifyBone_9();
    void* get_AnimGraphNode_SaveCachedPose_16();
    void* get_AnimGraphNode_SequencePlayer_12();
    void* get_AnimGraphNode_SaveCachedPose_15();
    void* get_AnimGraphNode_SequencePlayer_11();
    void* get_AnimGraphNode_LocalToComponentSpace_7();
    void* get_AnimGraphNode_SequenceEvaluator_3();
    void* get_AnimGraphNode_TwoWayBlend_3();
    void* get_AnimGraphNode_ComponentToLocalSpace_7();
    void* get_AnimGraphNode_BlendSpacePlayer_7();
    void* get_AnimGraphNode_SaveCachedPose_14();
    void* get_AnimGraphNode_LocalToComponentSpace_6();
    void* get_AnimGraphNode_ModifyBone_8();
    void* get_AnimGraphNode_ModifyBone_7();
    void* get_AnimGraphNode_ModifyBone_6();
    void* get_AnimGraphNode_LocalToComponentSpace_5();
    void* get_AnimGraphNode_SaveCachedPose_13();
    void* get_AnimGraphNode_ComponentToLocalSpace_6();
    void* get_AnimGraphNode_MakeDynamicAdditive();
    void* get_AnimGraphNode_SequenceEvaluator_2();
    void* get_AnimGraphNode_SaveCachedPose_12();
    void* get_AnimGraphNode_ApplyAdditive_3();
    void* get_AnimGraphNode_UseCachedPose_21();
    void* get_AnimGraphNode_ApplyAdditive_2();
    void* get_AnimGraphNode_UseCachedPose_20();
    void* get_AnimGraphNode_UseCachedPose_19();
    void* get_AnimGraphNode_SaveCachedPose_11();
    void* get_AnimGraphNode_UseCachedPose_18();
    void* get_AnimGraphNode_RotateRootBone_3();
    void* get_AnimGraphNode_ApplyAdditive_1();
    void* get_AnimGraphNode_ResetRoot_2();
    void* get_AnimGraphNode_ComponentToLocalSpace_5();
    void* get_AnimGraphNode_ModifyBone_5();
    void* get_AnimGraphNode_SequenceEvaluator_1();
    void* get_AnimGraphNode_RotateRootBone_2();
    void* get_AnimGraphNode_TwoWayBlend_2();
    void* get_AnimGraphNode_SequenceEvaluator();
    void* get_AnimGraphNode_UseCachedPose_17();
    void* get_AnimGraphNode_UseCachedPose_16();
    void* get_AnimGraphNode_ControlRig_4();
    void* get_AnimGraphNode_ControlRig_3();
    void* get_AnimGraphNode_ComponentToLocalSpace_4();
    void* get_AnimGraphNode_ModifyBone_4();
    void* get_AnimGraphNode_SequencePlayer_10();
    void* get_AnimGraphNode_LocalToComponentSpace_4();
    void* get_AnimGraphNode_RotateRootBone_1();
    void* get_AnimGraphNode_LookAt_3();
    void* get_AnimGraphNode_LocalToComponentSpace_3();
    void* get_AnimGraphNode_BlendSpacePlayer_6();
    void* get_AnimGraphNode_LayeredBoneBlend_9();
    void* get_AnimGraphNode_ModifyBone_3();
    void* get_AnimGraphNode_ResetRoot_1();
    void* get_AnimGraphNode_ComponentToLocalSpace_3();
    void* get_AnimGraphNode_ModifyBone_2();
    void* get_AnimGraphNode_SaveCachedPose_10();
    void* get_AnimGraphNode_TransitionResult_8();
    void* get_AnimGraphNode_TransitionResult_7();
    void* get_AnimGraphNode_SequencePlayer_9();
    void* get_AnimGraphNode_StateResult_7();
    void* get_AnimGraphNode_UseCachedPose_15();
    void* get_AnimGraphNode_StateResult_6();
    void* get_AnimGraphNode_StateMachine_2();
    void* get_AnimGraphNode_SaveCachedPose_9();
    void* get_AnimGraphNode_TwoWayBlend_1();
    void* get_AnimGraphNode_UseCachedPose_14();
    void* get_AnimGraphNode_UseCachedPose_13();
    void* get_AnimGraphNode_SaveCachedPose_8();
    void* get_AnimGraphNode_SequencePlayer_8();
    void* get_AnimGraphNode_TransitionResult_6();
    void* get_AnimGraphNode_TransitionResult_5();
    void* get_AnimGraphNode_TransitionResult_4();
    void* get_AnimGraphNode_TransitionResult_3();
    void* get_AnimGraphNode_TransitionResult_2();
    void* get_AnimGraphNode_SequencePlayer_7();
    void* get_AnimGraphNode_StateResult_5();
    void* get_AnimGraphNode_SequencePlayer_6();
    void* get_AnimGraphNode_StateResult_4();
    void* get_AnimGraphNode_SequencePlayer_5();
    void* get_AnimGraphNode_ControlRig_2();
    void* get_AnimGraphNode_ControlRig_1();
    void* get_AnimGraphNode_StateResult_3();
    void* get_AnimGraphNode_UseCachedPose_12();
    void* get_AnimGraphNode_StateResult_2();
    void* get_AnimGraphNode_StateMachine_1();
    void* get_AnimGraphNode_SequencePlayer_4();
    void* get_AnimGraphNode_TransitionResult_1();
    void* get_AnimGraphNode_TransitionResult();
    void* get_AnimGraphNode_SequencePlayer_3();
    void* get_AnimGraphNode_StateResult_1();
    void* get_AnimGraphNode_SequencePlayer_2();
    void* get_AnimGraphNode_StateResult();
    void* get_AnimGraphNode_StateMachine();
    void* get_AnimGraphNode_LocalToComponentSpace_2();
    void* get_AnimGraphNode_LayeredBoneBlend_8();
    void* get_AnimGraphNode_LayeredBoneBlend_7();
    void* get_AnimGraphNode_SaveCachedPose_7();
    void* get_AnimGraphNode_RotateRootBone();
    void* get_AnimGraphNode_ResetRoot();
    void* get_AnimGraphNode_LayeredBoneBlend_6();
    void* get_AnimGraphNode_SaveCachedPose_6();
    void* get_AnimGraphNode_UseCachedPose_11();
    void* get_AnimGraphNode_Slot_3();
    void* get_AnimGraphNode_Slot_2();
    void* get_AnimGraphNode_UseCachedPose_10();
    void* get_AnimGraphNode_UseCachedPose_9();
    void* get_AnimGraphNode_LayeredBoneBlend_5();
    void* get_AnimGraphNode_UseCachedPose_8();
    void* get_AnimGraphNode_UseCachedPose_7();
    void* get_AnimGraphNode_SaveCachedPose_5();
    void* get_AnimGraphNode_Slot_1();
    void* get_AnimGraphNode_Slot();
    void* get_AnimGraphNode_UseCachedPose_6();
    void* get_AnimGraphNode_LayeredBoneBlend_4();
    void* get_AnimGraphNode_SequencePlayer_1();
    void* get_AnimGraphNode_ApplyAdditive();
    void* get_AnimGraphNode_UseCachedPose_5();
    void* get_AnimGraphNode_RigidBody();
    void* get_AnimGraphNode_LocalToComponentSpace_1();
    void* get_AnimGraphNode_ComponentToLocalSpace_2();
    void* get_AnimGraphNode_SaveCachedPose_4();
    void* get_AnimGraphNode_TwoWayBlend();
    void* get_AnimGraphNode_ComponentToLocalSpace_1();
    void* get_AnimGraphNode_ModifyBone_1();
    void* get_AnimGraphNode_BlendSpacePlayer_5();
    void* get_AnimGraphNode_SaveCachedPose_3();
    void* get_AnimGraphNode_Root();
    void* get_AnimGraphNode_BlendListByBool_3();
    void* get_AnimGraphNode_LayeredBoneBlend_3();
    void* get_AnimGraphNode_BlendSpacePlayer_4();
    void* get_AnimGraphNode_BlendSpacePlayer_3();
    void* get_AnimGraphNode_SaveCachedPose_2();
    void* get_AnimGraphNode_UseCachedPose_4();
    void* get_AnimGraphNode_BlendListByBool_2();
    void* get_AnimGraphNode_UseCachedPose_3();
    void* get_AnimGraphNode_SequencePlayer();
    void* get_AnimGraphNode_LayeredBoneBlend_2();
    void* get_AnimGraphNode_LookAt_2();
    void* get_AnimGraphNode_LocalToComponentSpace();
    void* get_AnimGraphNode_ComponentToLocalSpace();
    void* get_AnimGraphNode_SaveCachedPose_1();
    void* get_AnimGraphNode_UseCachedPose_2();
    void* get_AnimGraphNode_LookAt_1();
    void* get_AnimGraphNode_LookAt();
    void* get_AnimGraphNode_ModifyBone();
    void* get_AnimGraphNode_ControlRig();
    void* get_AnimGraphNode_LayeredBoneBlend_1();
    void* get_AnimGraphNode_SaveCachedPose();
    void* get_AnimGraphNode_BlendListByBool_1();
    void* get_AnimGraphNode_UseCachedPose_1();
    void* get_AnimGraphNode_UseCachedPose();
    void* get_AnimGraphNode_BlendSpacePlayer_2();
    void* get_AnimGraphNode_BlendSpacePlayer_1();
    void* get_AnimGraphNode_LayeredBoneBlend();
    void* get_AnimGraphNode_BlendListByBool();
    void* get_AnimGraphNode_BlendSpacePlayer();
    void* get_Test_Hand_Position();
    _Game_Player_Mommy_GimbalMommyLongLegs_BP_NetworkMommy::BP_NetworkMommy_C*& get_NetworkMommy();
    void* get_Test_Hand_Position_Offset();
    bool get_Crouching();
    void set_Crouching(bool value);
    float& get_Delta_Seconds();
    float& get_Mesh_Scale();
    float& get_Actor_Rotation();
    float& get_Test_Hand_Rotation();
    float& get_Horizontal_Speed();
    bool get_Turning();
    void set_Turning(bool value);
    bool get_Moving_Horizontally();
    void set_Moving_Horizontally(bool value);
    void* get_LimbNames();
    void* get_LimbCurves();
    void* get_LimbPositions();
    void* get_CurrentLimbKey();
    void* get_LimbRotations();
    void* get_LimbPositionOffsets();
    void* get_World_Transform();
    float& get_Target_Root_Rotation();
    float& get_Root_Rotation();
    float& get_Smoothed_Root_Rotation();
    float& get_Previous_Smoothed_Root_Rotation();
    float& get_Turn_Weight();
    float& get_Root_Rotation_Offset();
    float& get_Turn_Explicit_Time();
    void* get_Slope_Rotation();
    float& get_Aim_Pitch();
    bool get_Shooting_Webs();
    void set_Shooting_Webs(bool value);
    void* get_Grapple_Target();
    bool get_Is_Grappling();
    void set_Is_Grappling(bool value);
    bool get_Moving_Backwards();
    void set_Moving_Backwards(bool value);
    bool get_Is_Carrying();
    void set_Is_Carrying(bool value);
    float& get_Carrying_Weight();
    void* get_Grapple_Attached_Normal();
    bool get_Is_Grapple_Attached();
    void set_Is_Grapple_Attached(bool value);
    float& get_Grapple_Attached_Weight();
    bool get_Is_Jumpscare_Active();
    void set_Is_Jumpscare_Active(bool value);
    bool get_Is_Falling();
    void set_Is_Falling(bool value);
    void* get_Smoothed_Rotation_A();
    void* get_Look_Position_A();
    void* get_Smoothed_Rotation_B();
    void* get_Look_Position_B();
    float& get_Crouch_Weight_A();
    bool get_Is_Player_Controlled();
    void set_Is_Player_Controlled(bool value);
    bool get_Is_Sitting();
    void set_Is_Sitting(bool value);
    bool get_Is_Dancing();
    void set_Is_Dancing(bool value);
    static _Script_CoreUObject::Class* static_class();
    void AnimGraph(_Script_Engine::PoseLink& AnimGraph);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_4E51CD9D4E0EBFFBCD523F9FA754E2A5();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_LookAt_DB8A77B847C8C3CFBD176F9982716C18();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_736440A24B9A85ABCA8647AA6D8CF71E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TwoWayBlend_1046554A4B444A201F3190951D8DB7A8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_1070011F475EA336E0422B8FA6B6A3D4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_407076134DC68F4B853ABB8004700F22();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_344B77BB40F7533346C8B198486A3B2E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_B2F7D135443999A1D91ACA8BD58533C8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_LayeredBoneBlend_064C90CE45975979B2C55CB368696E7F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_RotateRootBone_7945ADF24D19E15BAEEB3590C5697A08();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_46D9C61141A5F429693E06B1778E0C89();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_RotateRootBone_B36200894CFDAEB8C1C83B8F07761AD8();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_CFCC48C1482F62633FF6DBB391366E6E();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_RotateRootBone_44AC24764201AC084ABB2E9DC7F851C1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_AA6F7FC347FDAFD0D12ED2BA23EA9345();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_RotateRootBone_7CBB724E441A8302B20974BD62410A1F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_ModifyBone_5A5A59D44F1362835ACB1DAC45A61E46();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TransitionResult_4A5ACE5640B9C7D13DBC089B78F6E956();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TransitionResult_D4165BCD41F6BA662181358FC2F310E3();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TransitionResult_C831DFD24EA44A9216E3858FBFA93BE6();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TransitionResult_3BBE7C7448A074F42A060BAB9D99E6D1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MommyLongLegs_AnimGraphNode_TransitionResult_F556875342C8E3AE77A17A9058440356();
    void BlueprintUpdateAnimation0(float DeltaTimeX);
    void Play_Emote(int32_t Table_Index);
    void Play_Jumpscare_Animation();
    void ExecuteUbergraph_ABP_MommyLongLegs(int32_t EntryPoint);
}; // Size: 0x8d50
#pragma pack(pop)
}
