#pragma once
#include <Windows.h>
#include <cstdint>
#include <string>
#include <string_view>
#include "..\_Script_Engine\AnimInstance.hpp"
namespace _Game_Player_Huggy_BP_NetworkHuggy {
struct BP_NetworkHuggy_C;
}
namespace _Script_Engine {
struct Pawn;
}
namespace _Script_CoreUObject {
struct Class;
}
namespace _Script_Engine {
struct PoseLink;
}
namespace _Game_World_Geometry_Characters_Huggy_Animations_ABP_NetworkHuggy {
#pragma pack(push, 1)
struct ABP_NetworkHuggy_C : public _Script_Engine::AnimInstance {
    private: char pad_2c0[0x4ed0]; public:
    void* get_UberGraphFrame();
    void* get_AnimGraphNode_ControlRig_2();
    void* get_AnimGraphNode_ControlRig_1();
    void* get_AnimGraphNode_ControlRig();
    void* get_AnimGraphNode_Slot_4();
    void* get_AnimGraphNode_TwoWayBlend_4();
    void* get_AnimGraphNode_SaveCachedPose_9();
    void* get_AnimGraphNode_TransitionResult_33();
    void* get_AnimGraphNode_TransitionResult_32();
    void* get_AnimGraphNode_SequencePlayer_11();
    void* get_AnimGraphNode_StateResult_14();
    void* get_AnimGraphNode_UseCachedPose_17();
    void* get_AnimGraphNode_StateResult_13();
    void* get_AnimGraphNode_StateMachine_2();
    void* get_AnimGraphNode_BlendSpacePlayer_2();
    void* get_AnimGraphNode_SaveCachedPose_8();
    void* get_AnimGraphNode_BlendSpacePlayer_1();
    void* get_AnimGraphNode_ComponentToLocalSpace_1();
    void* get_AnimGraphNode_SaveCachedPose_7();
    void* get_AnimGraphNode_UseCachedPose_16();
    void* get_AnimGraphNode_LocalToComponentSpace_1();
    void* get_AnimGraphNode_ModifyBone_1();
    void* get_AnimGraphNode_RotateRootBone();
    void* get_AnimGraphNode_SaveCachedPose_6();
    void* get_AnimGraphNode_UseCachedPose_15();
    void* get_AnimGraphNode_UseCachedPose_14();
    void* get_AnimGraphNode_Slot_3();
    void* get_AnimGraphNode_LayeredBoneBlend_12();
    void* get_AnimGraphNode_LayeredBoneBlend_11();
    void* get_AnimGraphNode_UseCachedPose_13();
    void* get_AnimGraphNode_UseCachedPose_12();
    void* get_AnimGraphNode_BlendBoneByChannel_1();
    void* get_AnimGraphNode_LayeredBoneBlend_10();
    void* get_AnimGraphNode_SequenceEvaluator_12();
    void* get_AnimGraphNode_TwoWayBlend_3();
    void* get_AnimGraphNode_SequenceEvaluator_11();
    void* get_AnimGraphNode_SequenceEvaluator_10();
    void* get_AnimGraphNode_SequenceEvaluator_9();
    void* get_AnimGraphNode_TwoWayBlend_2();
    void* get_AnimGraphNode_TransitionResult_31();
    void* get_AnimGraphNode_TransitionResult_30();
    void* get_AnimGraphNode_TransitionResult_29();
    void* get_AnimGraphNode_TransitionResult_28();
    void* get_AnimGraphNode_TransitionResult_27();
    void* get_AnimGraphNode_TransitionResult_26();
    void* get_AnimGraphNode_TransitionResult_25();
    void* get_AnimGraphNode_TransitionResult_24();
    void* get_AnimGraphNode_TransitionResult_23();
    void* get_AnimGraphNode_TransitionResult_22();
    void* get_AnimGraphNode_TransitionResult_21();
    void* get_AnimGraphNode_TransitionResult_20();
    void* get_AnimGraphNode_TransitionResult_19();
    void* get_AnimGraphNode_TransitionResult_18();
    void* get_AnimGraphNode_TransitionResult_17();
    void* get_AnimGraphNode_TransitionResult_16();
    void* get_AnimGraphNode_TransitionResult_15();
    void* get_AnimGraphNode_TransitionResult_14();
    void* get_AnimGraphNode_TransitionResult_13();
    void* get_AnimGraphNode_TransitionResult_12();
    void* get_AnimGraphNode_TransitionResult_11();
    void* get_AnimGraphNode_TransitionResult_10();
    void* get_AnimGraphNode_TransitionResult_9();
    void* get_AnimGraphNode_TransitionResult_8();
    void* get_AnimGraphNode_TransitionResult_7();
    void* get_AnimGraphNode_TransitionResult_6();
    void* get_AnimGraphNode_TransitionResult_5();
    void* get_AnimGraphNode_SequencePlayer_10();
    void* get_AnimGraphNode_StateResult_12();
    void* get_AnimGraphNode_SequenceEvaluator_8();
    void* get_AnimGraphNode_StateResult_11();
    void* get_AnimGraphNode_SequencePlayer_9();
    void* get_AnimGraphNode_StateResult_10();
    void* get_AnimGraphNode_SequencePlayer_8();
    void* get_AnimGraphNode_StateResult_9();
    void* get_AnimGraphNode_TransitionResult_4();
    void* get_AnimGraphNode_UseCachedPose_11();
    void* get_AnimGraphNode_ApplyAdditive_1();
    void* get_AnimGraphNode_MakeDynamicAdditive_1();
    void* get_AnimGraphNode_SequenceEvaluator_7();
    void* get_AnimGraphNode_UseCachedPose_10();
    void* get_AnimGraphNode_LayeredBoneBlend_9();
    void* get_AnimGraphNode_SequencePlayer_7();
    void* get_AnimGraphNode_StateResult_8();
    void* get_AnimGraphNode_LayeredBoneBlend_8();
    void* get_AnimGraphNode_SequencePlayer_6();
    void* get_AnimGraphNode_UseCachedPose_9();
    void* get_AnimGraphNode_StateResult_7();
    void* get_AnimGraphNode_TransitionResult_3();
    void* get_AnimGraphNode_SequenceEvaluator_6();
    void* get_AnimGraphNode_StateResult_6();
    void* get_AnimGraphNode_SequencePlayer_5();
    void* get_AnimGraphNode_StateResult_5();
    void* get_AnimGraphNode_TransitionResult_2();
    void* get_AnimGraphNode_SequencePlayer_4();
    void* get_AnimGraphNode_StateResult_4();
    void* get_AnimGraphNode_UseCachedPose_8();
    void* get_AnimGraphNode_StateResult_3();
    void* get_AnimGraphNode_UseCachedPose_7();
    void* get_AnimGraphNode_StateResult_2();
    void* get_AnimGraphNode_StateMachine_1();
    void* get_AnimGraphNode_SaveCachedPose_5();
    void* get_AnimGraphNode_SequencePlayer_3();
    void* get_AnimGraphNode_SequencePlayer_2();
    void* get_AnimGraphNode_LayeredBoneBlend_7();
    void* get_AnimGraphNode_SequenceEvaluator_5();
    void* get_AnimGraphNode_SequenceEvaluator_4();
    void* get_AnimGraphNode_LayeredBoneBlend_6();
    void* get_AnimGraphNode_BlendSpacePlayer();
    void* get_AnimGraphNode_BlendBoneByChannel();
    void* get_AnimGraphNode_TwoWayBlend_1();
    void* get_AnimGraphNode_SaveCachedPose_4();
    void* get_AnimGraphNode_SaveCachedPose_3();
    void* get_AnimGraphNode_UseCachedPose_6();
    void* get_AnimGraphNode_Slot_2();
    void* get_AnimGraphNode_UseCachedPose_5();
    void* get_AnimGraphNode_LayeredBoneBlend_5();
    void* get_AnimGraphNode_SaveCachedPose_2();
    void* get_AnimGraphNode_UseCachedPose_4();
    void* get_AnimGraphNode_UseCachedPose_3();
    void* get_AnimGraphNode_Slot_1();
    void* get_AnimGraphNode_LayeredBoneBlend_4();
    void* get_AnimGraphNode_SequenceEvaluator_3();
    void* get_AnimGraphNode_SequenceEvaluator_2();
    void* get_AnimGraphNode_Slot();
    void* get_AnimGraphNode_MakeDynamicAdditive();
    void* get_AnimGraphNode_LayeredBoneBlend_3();
    void* get_AnimGraphNode_ApplyAdditive();
    void* get_AnimGraphNode_LayeredBoneBlend_2();
    void* get_AnimGraphNode_TwoWayBlend();
    void* get_AnimGraphNode_SequenceEvaluator_1();
    void* get_AnimGraphNode_SequenceEvaluator();
    void* get_AnimGraphNode_SaveCachedPose_1();
    void* get_AnimGraphNode_UseCachedPose_2();
    void* get_AnimGraphNode_UseCachedPose_1();
    void* get_AnimGraphNode_ModifyBone();
    void* get_AnimGraphNode_LayeredBoneBlend_1();
    void* get_AnimGraphNode_BoneDrivenController_6();
    void* get_AnimGraphNode_BoneDrivenController_5();
    void* get_AnimGraphNode_BoneDrivenController_4();
    void* get_AnimGraphNode_BoneDrivenController_3();
    void* get_AnimGraphNode_BoneDrivenController_2();
    void* get_AnimGraphNode_BoneDrivenController_1();
    void* get_AnimGraphNode_BoneDrivenController();
    void* get_AnimGraphNode_LocalToComponentSpace();
    void* get_AnimGraphNode_ComponentToLocalSpace();
    void* get_AnimGraphNode_Root();
    void* get_AnimGraphNode_SaveCachedPose();
    void* get_AnimGraphNode_TransitionResult_1();
    void* get_AnimGraphNode_TransitionResult();
    void* get_AnimGraphNode_SequencePlayer_1();
    void* get_AnimGraphNode_StateResult_1();
    void* get_AnimGraphNode_UseCachedPose();
    void* get_AnimGraphNode_StateResult();
    void* get_AnimGraphNode_StateMachine();
    void* get_AnimGraphNode_LayeredBoneBlend();
    void* get_AnimGraphNode_SequencePlayer();
    _Game_Player_Huggy_BP_NetworkHuggy::BP_NetworkHuggy_C*& get_Network_Huggy();
    _Script_Engine::Pawn*& get_Pawn();
    float& get_Delta_Seconds();
    float& get_Horizontal_Speed();
    float& get_Vertical_Speed();
    float& get_Target_Root_Rotation();
    float& get_Root_Rotation();
    float& get_Previous_Smoothed_Root_Rotation();
    float& get_Smoothed_Root_Rotation();
    float& get_Turn_Weight();
    float& get_Root_Rotation_Offset();
    float& get_Head_Pitch();
    float& get_Crouch_Weight();
    float& get_Backwards_Weight();
    float& get_Smoothed_Horizontal_Speed();
    void* get_Velocity();
    bool get_Is_Charging();
    void set_Is_Charging(bool value);
    bool get_Is_Moving();
    void set_Is_Moving(bool value);
    bool get_Is_Jumpscare_Active();
    void set_Is_Jumpscare_Active(bool value);
    bool get_Is_Falling();
    void set_Is_Falling(bool value);
    bool get_Is_Sitting();
    void set_Is_Sitting(bool value);
    float& get_Turn_Explicit();
    bool get_Is_Locally_Controlled();
    void set_Is_Locally_Controlled(bool value);
    bool get_Is_Dancing();
    void set_Is_Dancing(bool value);
    bool get_Is_Carrying();
    void set_Is_Carrying(bool value);
    float& get_Carrying_Weight();
    bool get_Is_Bashing();
    void set_Is_Bashing(bool value);
    float& get_Bashing_Weight();
    static _Script_CoreUObject::Class* static_class();
    void AnimGraph(_Script_Engine::PoseLink& AnimGraph);
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_LayeredBoneBlend_2070EFC14D85A6229501AAAC25871A5F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_ModifyBone_3DDDF23A4F074B8D075AA39462F3F9EC();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TwoWayBlend_6F777FCF4A45354BAEE500876518D794();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_ControlRig_D7C988D842AA413D80A54C92B4B01617();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_ControlRig_8DAE2AEA4B28CC80CCF5A882010C37A1();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_ModifyBone_4FF1550E46DDD3AC44E3EE89412B3ECC();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_869731694E8B5A25AE882C92D0BD6A01();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_89094A9C411FFB76F5FFACA1B409597F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_D1D9EA0A4BB1A9F3C1B6F3863E7CEC39();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_7ABAAD64440D789FDB6810A0B6B3E0EF();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_D62D25884CB8637E1805FD966375B2E4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_FD8BF29848BA35AE94EE6F8F9BC7C14D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_A48B36B2427F1AEE09DBF5A6888F5592();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_39B4EF374701BCD60945FDA1FC60F50D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_NetworkHuggy_AnimGraphNode_TransitionResult_D63551C74A10A1E3FE49CF9437D7C8FA();
    void BlueprintUpdateAnimation0(float DeltaTimeX);
    void Play_Attack_Animation();
    void BlueprintBeginPlay0();
    void Emote_Debug();
    void Play_Emote(int32_t Table_Index);
    void Play_Jumpscare_Animation();
    void Play_Bash_Animation();
    void ExecuteUbergraph_ABP_NetworkHuggy(int32_t EntryPoint);
}; // Size: 0x5190
#pragma pack(pop)
}
