#pragma once
#include <Windows.h>
#include <cstdint>
#include <string>
#include <string_view>
#include "..\_Script_Engine\AnimInstance.hpp"
namespace _Game_Player_TrainingDummy_CPPChildren_BP_NetworkCharacter {
struct BP_NetworkCharacter_C;
}
namespace _Script_Engine {
struct AnimSequenceBase;
}
namespace _Script_CoreUObject {
struct Class;
}
namespace _Script_Engine {
struct PoseLink;
}
namespace _Script_Engine {
struct AnimSequence;
}
namespace _Game_World_Geometry_Characters_PlayerCharacter_Animations_ABP_FirstPersonGuns {
#pragma pack(push, 1)
struct ABP_FirstPersonGuns_C : public _Script_Engine::AnimInstance {
    private: char pad_2c0[0x4200]; public:
    void* get_UberGraphFrame();
    void* get_AnimGraphNode_TransitionResult_33();
    void* get_AnimGraphNode_TransitionResult_32();
    void* get_AnimGraphNode_TransitionResult_31();
    void* get_AnimGraphNode_TransitionResult_30();
    void* get_AnimGraphNode_ComponentToLocalSpace_9();
    void* get_AnimGraphNode_ModifyBone_10();
    void* get_AnimGraphNode_LocalToComponentSpace_9();
    void* get_AnimGraphNode_ModifyBone_9();
    void* get_AnimGraphNode_SequencePlayer_21();
    void* get_AnimGraphNode_StateResult_19();
    void* get_AnimGraphNode_LayeredBoneBlend_8();
    void* get_AnimGraphNode_UseCachedPose_10();
    void* get_AnimGraphNode_ComponentToLocalSpace_8();
    void* get_AnimGraphNode_ModifyBone_8();
    void* get_AnimGraphNode_LocalToComponentSpace_8();
    void* get_AnimGraphNode_ModifyBone_7();
    void* get_AnimGraphNode_SequencePlayer_20();
    void* get_AnimGraphNode_StateResult_18();
    void* get_AnimGraphNode_ComponentToLocalSpace_7();
    void* get_AnimGraphNode_ModifyBone_6();
    void* get_AnimGraphNode_LocalToComponentSpace_7();
    void* get_AnimGraphNode_ModifyBone_5();
    void* get_AnimGraphNode_SequencePlayer_19();
    void* get_AnimGraphNode_StateResult_17();
    void* get_AnimGraphNode_UseCachedPose_9();
    void* get_AnimGraphNode_StateResult_16();
    void* get_AnimGraphNode_StateMachine_4();
    void* get_AnimGraphNode_SaveCachedPose_4();
    void* get_AnimGraphNode_SaveCachedPose_3();
    void* get_AnimGraphNode_TransitionResult_29();
    void* get_AnimGraphNode_TransitionResult_28();
    void* get_AnimGraphNode_SequencePlayer_18();
    void* get_AnimGraphNode_StateResult_15();
    void* get_AnimGraphNode_UseCachedPose_8();
    void* get_AnimGraphNode_StateResult_14();
    void* get_AnimGraphNode_StateMachine_3();
    void* get_AnimGraphNode_LayeredBoneBlend_7();
    void* get_AnimGraphNode_SaveCachedPose_2();
    void* get_AnimGraphNode_BlendSpacePlayer_1();
    void* get_AnimGraphNode_TransitionResult_27();
    void* get_AnimGraphNode_TransitionResult_26();
    void* get_AnimGraphNode_TransitionResult_25();
    void* get_AnimGraphNode_TransitionResult_24();
    void* get_AnimGraphNode_TransitionResult_23();
    void* get_AnimGraphNode_TransitionResult_22();
    void* get_AnimGraphNode_TransitionResult_21();
    void* get_AnimGraphNode_TransitionResult_20();
    void* get_AnimGraphNode_TransitionResult_19();
    void* get_AnimGraphNode_TransitionResult_18();
    void* get_AnimGraphNode_TransitionResult_17();
    void* get_AnimGraphNode_TransitionResult_16();
    void* get_AnimGraphNode_TransitionResult_15();
    void* get_AnimGraphNode_TransitionResult_14();
    void* get_AnimGraphNode_TransitionResult_13();
    void* get_AnimGraphNode_BlendSpacePlayer();
    void* get_AnimGraphNode_StateResult_13();
    void* get_AnimGraphNode_SequencePlayer_17();
    void* get_AnimGraphNode_StateResult_12();
    void* get_AnimGraphNode_SequencePlayer_16();
    void* get_AnimGraphNode_StateResult_11();
    void* get_AnimGraphNode_SequencePlayer_15();
    void* get_AnimGraphNode_StateResult_10();
    void* get_AnimGraphNode_TransitionResult_12();
    void* get_AnimGraphNode_UseCachedPose_7();
    void* get_AnimGraphNode_StateResult_9();
    void* get_AnimGraphNode_SequencePlayer_14();
    void* get_AnimGraphNode_StateResult_8();
    void* get_AnimGraphNode_StateMachine_2();
    void* get_AnimGraphNode_Root();
    void* get_AnimGraphNode_UseCachedPose_6();
    void* get_AnimGraphNode_SequencePlayer_13();
    void* get_AnimGraphNode_TwoWayBlend_2();
    void* get_AnimGraphNode_SaveCachedPose_1();
    void* get_AnimGraphNode_TransitionResult_11();
    void* get_AnimGraphNode_TransitionResult_10();
    void* get_AnimGraphNode_TransitionResult_9();
    void* get_AnimGraphNode_TransitionResult_8();
    void* get_AnimGraphNode_TransitionResult_7();
    void* get_AnimGraphNode_TransitionResult_6();
    void* get_AnimGraphNode_SequencePlayer_12();
    void* get_AnimGraphNode_LayeredBoneBlend_6();
    void* get_AnimGraphNode_SequencePlayer_11();
    void* get_AnimGraphNode_StateResult_7();
    void* get_AnimGraphNode_ComponentToLocalSpace_6();
    void* get_AnimGraphNode_LocalToComponentSpace_6();
    void* get_AnimGraphNode_LookAt_1();
    void* get_AnimGraphNode_SequencePlayer_10();
    void* get_AnimGraphNode_StateResult_6();
    void* get_AnimGraphNode_SequencePlayer_9();
    void* get_AnimGraphNode_TwoWayBlend_1();
    void* get_AnimGraphNode_SequencePlayer_8();
    void* get_AnimGraphNode_LayeredBoneBlend_5();
    void* get_AnimGraphNode_SequencePlayer_7();
    void* get_AnimGraphNode_StateResult_5();
    void* get_AnimGraphNode_SequenceEvaluator_3();
    void* get_AnimGraphNode_StateResult_4();
    void* get_AnimGraphNode_StateMachine_1();
    void* get_AnimGraphNode_UseCachedPose_5();
    void* get_AnimGraphNode_MakeDynamicAdditive_1();
    void* get_AnimGraphNode_ApplyAdditive_1();
    void* get_AnimGraphNode_SequenceEvaluator_2();
    void* get_AnimGraphNode_TransitionResult_5();
    void* get_AnimGraphNode_TransitionResult_4();
    void* get_AnimGraphNode_TransitionResult_3();
    void* get_AnimGraphNode_TransitionResult_2();
    void* get_AnimGraphNode_TransitionResult_1();
    void* get_AnimGraphNode_TransitionResult();
    void* get_AnimGraphNode_SequencePlayer_6();
    void* get_AnimGraphNode_LayeredBoneBlend_4();
    void* get_AnimGraphNode_SequencePlayer_5();
    void* get_AnimGraphNode_StateResult_3();
    void* get_AnimGraphNode_ComponentToLocalSpace_5();
    void* get_AnimGraphNode_LocalToComponentSpace_5();
    void* get_AnimGraphNode_LookAt();
    void* get_AnimGraphNode_SequencePlayer_4();
    void* get_AnimGraphNode_StateResult_2();
    void* get_AnimGraphNode_SequencePlayer_3();
    void* get_AnimGraphNode_TwoWayBlend();
    void* get_AnimGraphNode_SequencePlayer_2();
    void* get_AnimGraphNode_LayeredBoneBlend_3();
    void* get_AnimGraphNode_SequencePlayer_1();
    void* get_AnimGraphNode_StateResult_1();
    void* get_AnimGraphNode_SequenceEvaluator_1();
    void* get_AnimGraphNode_StateResult();
    void* get_AnimGraphNode_StateMachine();
    void* get_AnimGraphNode_MakeDynamicAdditive();
    void* get_AnimGraphNode_SequenceEvaluator();
    void* get_AnimGraphNode_ApplyAdditive();
    void* get_AnimGraphNode_LayeredBoneBlend_2();
    void* get_AnimGraphNode_LayeredBoneBlend_1();
    void* get_AnimGraphNode_SaveCachedPose();
    void* get_AnimGraphNode_BlendListByBool_2();
    void* get_AnimGraphNode_UseCachedPose_4();
    void* get_AnimGraphNode_LocalToComponentSpace_4();
    void* get_AnimGraphNode_ComponentToLocalSpace_4();
    void* get_AnimGraphNode_UseCachedPose_3();
    void* get_AnimGraphNode_ModifyBone_4();
    void* get_AnimGraphNode_BlendListByBool_1();
    void* get_AnimGraphNode_ModifyBone_3();
    void* get_AnimGraphNode_SequencePlayer();
    void* get_AnimGraphNode_LocalToComponentSpace_3();
    void* get_AnimGraphNode_ComponentToLocalSpace_3();
    void* get_AnimGraphNode_LayeredBoneBlend();
    void* get_AnimGraphNode_UseCachedPose_2();
    void* get_AnimGraphNode_ModifyBone_2();
    void* get_AnimGraphNode_ComponentToLocalSpace_2();
    void* get_AnimGraphNode_LocalToComponentSpace_2();
    void* get_AnimGraphNode_BlendListByBool();
    void* get_AnimGraphNode_UseCachedPose_1();
    void* get_AnimGraphNode_LocalToComponentSpace_1();
    void* get_AnimGraphNode_ComponentToLocalSpace_1();
    void* get_AnimGraphNode_UseCachedPose();
    void* get_AnimGraphNode_ModifyBone_1();
    void* get_AnimGraphNode_ModifyBone();
    void* get_AnimGraphNode_LocalToComponentSpace();
    void* get_AnimGraphNode_ComponentToLocalSpace();
    _Game_Player_TrainingDummy_CPPChildren_BP_NetworkCharacter::BP_NetworkCharacter_C*& get_Network_Character();
    float& get_Delta_Seconds();
    float& get_Horizontal_Speed();
    bool get_Is_Moving();
    void set_Is_Moving(bool value);
    bool get_Is_Sprinting();
    void set_Is_Sprinting(bool value);
    bool get_Guns_Lowered();
    void set_Guns_Lowered(bool value);
    _Script_Engine::AnimSequenceBase*& get_Gesture_Sequence();
    bool get_Is_Gesture_Active();
    void set_Is_Gesture_Active(bool value);
    bool get_Is_Falling();
    void set_Is_Falling(bool value);
    void* get_Control_Rotation();
    float& get_Vertical_Speed();
    bool get_Is_Falling_Up();
    void set_Is_Falling_Up(bool value);
    bool get_Right_Hand_Extended();
    void set_Right_Hand_Extended(bool value);
    bool get_Left_Hand_Extended();
    void set_Left_Hand_Extended(bool value);
    void* get_Right_Hand_Position();
    void* get_Left_Hand_Position();
    bool get_Is_Pulling_Right_Hand();
    void set_Is_Pulling_Right_Hand(bool value);
    bool get_Is_Pulling_Left_Hand();
    void set_Is_Pulling_Left_Hand(bool value);
    void* get_Noise();
    bool get_Is_Inside_Locker();
    void set_Is_Inside_Locker(bool value);
    bool get_Holding_Breath();
    void set_Holding_Breath(bool value);
    bool get_Can_Hold_Breath();
    void set_Can_Hold_Breath(bool value);
    float& get_Breath_Weight();
    bool get_Lock_Grabpack_Rotation();
    void set_Lock_Grabpack_Rotation(bool value);
    float& get_Lock_Grabpack_Rotation_Weight();
    bool get_Wants_To_Prone();
    void set_Wants_To_Prone(bool value);
    bool get_Is_Moving_Backward();
    void set_Is_Moving_Backward(bool value);
    float& get_Moving_Left_Right();
    float& get_Moving_Left_Right_Weight();
    void* get_Local_Movement_Direction_2D();
    bool get_ForceFirstPersonProne();
    void set_ForceFirstPersonProne(bool value);
    static _Script_CoreUObject::Class* static_class();
    void AnimGraph(_Script_Engine::PoseLink& AnimGraph);
    void OnRep_Guns_Lowered();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_ModifyBone_DACEA55A4A680A493B0A31BE3DC9B219();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_ModifyBone_162116C04BD4C914788F3495DCEC6A1B();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_ModifyBone_C19A24D44D87CDDA395702B0126AB1E4();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_ModifyBone_FDD902D443E792E8502E71810CA48991();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_ModifyBone_DD804EC044F03515BB041C825A0AA8BB();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_B3ACE2D94088CFD6CB8E4A83D55C3C09();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_A1B464B842AB235277F5FD924E6F9C8D();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_BlendSpacePlayer_3A85895D47F93AD8CCB267894151C16F();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_79FCE3974C0DD437666E61ACCDD23090();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_1523F23B4B0AA5B112A16E8C73C0C634();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_E6D2DED9428C92351F706197D5E84E78();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_7D62ABFA4C1B402F7FE2FB95B62193BB();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_05EC8DA64EC491FDA4B943A2EA14E751();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_5F5E04874173EF865F3AA387D385E085();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_364DB5ED411E40DD0C23F7AD71748524();
    void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_FirstPersonGuns_AnimGraphNode_TransitionResult_94EA8A4B44B7266632CB5A9D341F8E8C();
    void BlueprintUpdateAnimation0(float DeltaTimeX);
    void Play_Gesture(_Script_Engine::AnimSequence* Third_Person_Anim_Sequence);
    void BlueprintBeginPlay0();
    void Set_Prone();
    void SetForcedFirstPersonProne(bool ForceFirestPersonProne);
    void ExecuteUbergraph_ABP_FirstPersonGuns(int32_t EntryPoint);
}; // Size: 0x44c0
#pragma pack(pop)
}
